[package]
name = "graphix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphix_macros = { path = "../graphix_macros" }
strum = { version = "0.26.2", features = ["derive"] }
