[package]
name = "graphix_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
name = "graphix_macros"

[dependencies]
proc-macro2 = "1.0.82"
quote = "1.0.36"
strum = { version = "0.26.2", features = ["derive"] }
syn = { version = "2.0.61", features = ["full", "printing"] }

