[package]
name = "graphix_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphix = { path = "../graphix" }
hcl-rs = "0.16.9"
strum = "0.26.2"
uuid = { version = "1.8.0", features = ["v4"] }
